name = "overleaf"
main = "dist/index.js"
compatibility_date = "2025-04-09"
compatibility_flags = ["nodejs_compat"]
[vars]
BASE_URL = "https://dx4600pro-gwj.cn25.ug.link"
PORT = "7777"
USERNAME = "teardrop"

[[kv_namespaces]]
binding = "UGLINK_CACHE"
id = "f4f9f0e83bfe44dcb5a061cef9087fb8"  # Replace with your actual KV namespace ID from Cloudflare dashboard

[observability.logs]
enabled = true
